apiVersion: v1
kind: Service
metadata:
  name: cra
  labels:
    run: cra
spec:
  ports:
    - port: 80
      nodePort: 32767
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    run: cra
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: cra
    spec:
      containers:
        - name: cra
          image: simformniki/cra-docker:2
          ports:
            - containerPort: 80
